In [45]:
# imports
import pandas as pd
import numpy as np

# read csvs
df = pd.read_csv('./datasets/temperatura_aggregated.csv')
df_vendas = pd.read_csv('./datasets/vendas.csv', ';')

# pre processing
def get_dias_fechados():
    return ['2018-03-30', '2018-12-25', '2018-12-29', '2018-12-30', '2018-12-31', '2019-01-01', '2019-03-03', '2019-03-04', '2019-03-05', '2019-12-25', '2019-12-29', '2019-12-30', '2019-12-31', '2020-01-01', '2020-02-24', '2020-02-25']

def get_dias_fds():
    return ['Sunday', 'Saturday']

def get_dias_feriados():
    return ['2018-03-30', '2018-04-21', '2018-04-30', '2018-05-01', '2018-05-31', '2018-06-01', '2018-09-07', '2018-10-12', '2018-11-02', '2018-11-15', '2018-11-16', '2018-12-24', '2018-12-25', '2018-12-29', '2018-12-30', '2018-12-31', 
'2019-01-01', '2019-03-04', '2019-03-05', '2019-04-19', '2019-04-21', '2019-05-01', '2019-06-20', '2019-06-21', '2019-09-07', '2019-10-12', '2019-11-02', '2019-11-15', '2019-12-25', '2019-12-25', '2019-12-25', '2019-12-30', '2019-12-31', 
'2020-01-01', '2020-02-24', '2020-02-25']

def get_dias_festivos():
    return ['2018-05-13', '2018-08-12', '2018-12-25', '2018-12-29', '2018-12-30', '2018-12-31', '2019-01-01', '2019-03-03', '2019-03-04', '2019-03-05', '2019-05-12', '2019-08-11', '2019-12-25', '2019-12-29', '2019-12-30', '2019-12-31', '2020-01-01', '2020-02-24', '2020-02-25']

def get_vesperas_dias_festivos():
    vesperas = []
    for i in range(len(get_dias_festivos())):
        vesperas_dia_festivo_current = pd.Series(pd.date_range(end=get_dias_festivos()[i], periods=5, closed='left'))
        for j in range(len(vesperas_dia_festivo_current)):
            vesperas.append(vesperas_dia_festivo_current[j])
    return vesperas

def get_pos_dias_festivos():
    pos = []
    for i in range(len(get_dias_festivos())):
        pos_dia_festivo_current = pd.Series(pd.date_range(get_dias_festivos()[i], periods=3, closed='right'))
        for j in range(len(pos_dia_festivo_current)):
            pos.append(pos_dia_festivo_current[j])
    return pos

def get_dias_acerca_pagamento():
    return [5,6,7,8,9,10,28,29,30,31]

def get_meses_baixas_temporadas():
    return [1, 2]


# featured engineering
df.insert(loc=1, column='VENDAS', value=(df_vendas['VENDAS'].fillna(0).astype(int)))
df.insert(loc=2, column='IS_FECHADO', value=(pd.DatetimeIndex(df['DATA']).isin(get_dias_fechados()).astype(int)))
df.insert(loc=3, column='IS_FDS', value=(pd.DatetimeIndex(df['DATA']).day_name().isin(get_dias_fds())).astype(int))
df.insert(loc=4, column='IS_FERIADO', value=(pd.DatetimeIndex(df['DATA']).isin(get_dias_feriados())).astype(int))
df.insert(loc=5, column='IS_DATA_FESTIVA', value=(pd.DatetimeIndex(df['DATA']).isin(get_dias_festivos())).astype(int))
df.insert(loc=6, column='IS_VESPERA_DATA_FESTIVA', value=(pd.DatetimeIndex(df['DATA']).isin(get_vesperas_dias_festivos())).astype(int))
df.insert(loc=7, column='IS_POS_DATA_FESTIVA', value=(pd.DatetimeIndex(df['DATA']).isin(get_pos_dias_festivos())).astype(int))
df.insert(loc=8, column='IS_SEMANA_PAGAMENTO', value=(pd.DatetimeIndex(df['DATA']).day.astype(int).isin(get_dias_acerca_pagamento()).astype(int)))
df.insert(loc=9, column='IS_BAIXA_TEMPORADA', value=(pd.DatetimeIndex(df['DATA']).month.isin(get_meses_baixas_temporadas()).astype(int)))
df.insert(loc=10, column='QTD_CONCORRENTES', value=(0))
df

# a = df.query('DATA >= "2018-02-14" and DATA <= "2018-02-28"')
# a = df.query('IS_FECHADO == 1')
# a = df.query('IS_FERIADO == 1 and IS_FECHADO == 0')
# a = df.query('IS_DATA_FESTIVA == 1 and IS_FECHADO == 0')
# a = df.query('IS_VESPERA_DATA_FESTIVA == 1 and IS_FECHADO == 0')
# a = df.query('IS_POS_DATA_FESTIVA == 1 and IS_FECHADO == 0')
# a

,DATA,VENDAS,IS_FECHADO,IS_FDS,IS_FERIADO,IS_DATA_FESTIVA,IS_VESPERA_DATA_FESTIVA,IS_POS_DATA_FESTIVA,IS_SEMANA_PAGAMENTO,IS_BAIXA_TEMPORADA,QTD_CONCORRENTES,PRECIPITACAO,TEMPERATURA,UMIDADE
0,2018-02-14,132,0,0,0,0,0,0,0,1,0,0.0,28.0,66.75
1,2018-02-15,149,0,0,0,0,0,0,0,1,0,0.0,28.6,61.50
2,2018-02-16,130,0,0,0,0,0,0,0,1,0,0.0,30.6,65.25
3,2018-02-17,174,0,1,0,0,0,0,0,1,0,0.0,31.5,65.75
4,2018-02-18,185,0,1,0,0,0,0,0,1,0,0.0,33.4,58.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
747,2020-03-02,0,0,0,0,0,0,0,0,0,0,0.0,29.2,66.00
748,2020-03-03,0,0,0,0,0,0,0,0,0,0,0.0,30.0,70.00
749,2020-03-04,0,0,0,0,0,0,0,0,0,0,0.0,29.7,67.00
750,2020-03-05,0,0,0,0,0,0,0,1,0,0,0.0,28.8,67.00
751,2020-03-06,0,0,0,0,0,0,0,1,0,0,0.0,29.8,70.00