In [49]:
import pandas as pd
import numpy as np

# import data
df = pd.read_csv('./datasets/temperatura_aggregated.csv')

# adjust columns
df['IS_FDS'] = (pd.DatetimeIndex(df['DATA']).day_name().isin(['Sunday', 'Saturday'])).astype(int)
df['VENDAS'] = 0
df['IS_SEMANA_PAGAMENTO'] = 0
df['QTD_CONCORRENTES_ABERTOS'] = 0 
df['IS_ALTA_TEMPORADA'] = 0
df['IS_FERIADO'] = 0
df.head(40)

,DATA,PRECIPITACAO,TEMPERATURA,UMIDADE,IS_FDS,VENDAS,IS_SEMANA_PAGAMENTO,QTD_CONCORRENTES_ABERTOS,IS_ALTA_TEMPORADA,IS_FERIADO
0,2018-02-14,0.0,28.0,66.75,0,0,0,0,0,0
1,2018-02-15,0.0,28.6,61.50,0,0,0,0,0,0
2,2018-02-16,0.0,30.6,65.25,0,0,0,0,0,0
3,2018-02-17,0.0,31.5,65.75,1,0,0,0,0,0
4,2018-02-18,0.0,33.4,58.50,1,0,0,0,0,0
5,2018-02-19,0.0,29.0,75.25,0,0,0,0,0,0
6,2018-02-20,3.3,26.1,91.75,0,0,0,0,0,0
7,2018-02-21,27.0,29.2,82.75,0,0,0,0,0,0
8,2018-02-22,15.0,27.8,73.75,0,0,0,0,0,0
9,2018-02-23,0.0,28.8,73.50,0,0,0,0,0,0
10,2018-02-24,0.0,29.8,80.50,1,0,0,0,0,0
11,2018-02-25,0.0,29.8,74.00,1,0,0,0,0,0
12,2018-02-26,0.0,29.8,74.00,0,0,0,0,0,0
13,2018-02-27,0.0,30.5,85.25,0,0,0,0,0,0
14,2018-02-28,26.4,29.4,81.50,0,0,0,0,0,0
15,2018-03-01,0.0,31.0,82.50,0,0,0,0,0,0
16,2018-03-02,0.0,30.4,75.75,0,0,0,0,0,0
17,2018-03-03,0.0,29.8,74.00,1,0,0,0,0,0
18,2018-03-04,0.0,32.8,80.25,1,0,0,0,0,0
19,2018-03-05,8.2,31.5,79.50,0,0,0,0,0,0
20,2018-03-06,0.0,28.2,85.00,0,0,0,0,0,0
21,2018-03-07,0.7,26.7,63.00,0,0,0,0,0,0
22,2018-03-08,0.0,28.1,69.00,0,0,0,0,0,0
23,2018-03-09,0.0,27.8,76.75,0,0,0,0,0,0
24,2018-03-10,0.0,33.3,70.75,1,0,0,0,0,0
25,2018-03-11,0.0,34.7,63.25,1,0,0,0,0,0
26,2018-03-12,7.5,25.4,63.75,0,0,0,0,0,0
27,2018-03-13,0.0,28.8,58.00,0,0,0,0,0,0
28,2018-03-14,0.0,32.6,61.50,0,0,0,0,0,0
29,2018-03-15,33.3,27.3,79.25,0,0,0,0,0,0
30,2018-03-16,1.9,27.3,65.75,0,0,0,0,0,0
31,2018-03-17,0.0,33.0,72.75,1,0,0,0,0,0
32,2018-03-18,0.0,36.4,63.75,1,0,0,0,0,0
33,2018-03-19,7.5,29.0,74.00,0,0,0,0,0,0
34,2018-03-20,4.4,22.6,84.00,0,0,0,0,0,0
35,2018-03-21,2.0,24.8,76.00,0,0,0,0,0,0
36,2018-03-22,0.0,26.0,63.75,0,0,0,0,0,0
37,2018-03-23,0.0,33.1,70.00,0,0,0,0,0,0
38,2018-03-24,0.0,29.2,91.25,1,0,0,0,0,0
39,2018-03-25,26.9,24.1,78.50,1,0,0,0,0,0